version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - $(aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URL)
  build:
    commands:
      - echo Building the Docker image
      - docker build -t html-app . 
      - docker tag html-app:latest $ECR_REPO_URL:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR
      - docker push $ECR_REPO_URL:latest

artifacts:
  files:
    - '**/*'  # Adjust this if you want to include specific files
  base-directory: /usr/share/nginx/html 

